<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class WardsTableSeeder_2 extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('wards')->insert(array (
            0 => 
            array (
                'id' => 544,
                'ward_name' => 'Sankara',
                'lga' => 'Ringim',
                'state' => 'Jigawa',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            1 => 
            array (
                'id' => 545,
                'ward_name' => 'Buji',
                'lga' => 'Buji',
                'state' => 'Jigawa',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            2 => 
            array (
                'id' => 546,
                'ward_name' => 'Kawaya',
                'lga' => 'Buji',
                'state' => 'Jigawa',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            3 => 
            array (
                'id' => 547,
                'ward_name' => 'Duru',
                'lga' => 'Dutse',
                'state' => 'Jigawa',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            4 => 
            array (
                'id' => 548,
                'ward_name' => 'Kachi',
                'lga' => 'Dutse',
                'state' => 'Jigawa',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            5 => 
            array (
                'id' => 549,
                'ward_name' => 'Igbajo 1',
                'lga' => 'Boluwaduro',
                'state' => 'Osun',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            6 => 
            array (
                'id' => 550,
                'ward_name' => 'Igbajo 3',
                'lga' => 'Boluwaduro',
                'state' => 'Osun',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            7 => 
            array (
                'id' => 551,
                'ward_name' => 'Iresi 1',
                'lga' => 'Boluwaduro',
                'state' => 'Osun',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            8 => 
            array (
                'id' => 552,
                'ward_name' => 'Iresi  2',
                'lga' => 'Boluwaduro',
                'state' => 'Osun',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            9 => 
            array (
                'id' => 553,
                'ward_name' => 'Konda/5',
                'lga' => 'Irepodun',
                'state' => 'Osun',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            10 => 
            array (
                'id' => 554,
                'ward_name' => 'Afolu/7',
                'lga' => 'Irepodun',
                'state' => 'Osun',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            11 => 
            array (
                'id' => 555,
                'ward_name' => 'Agowande',
                'lga' => 'Olorunda',
                'state' => 'Osun',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            12 => 
            array (
                'id' => 556,
                'ward_name' => 'Ota Efun',
                'lga' => 'Olorunda',
                'state' => 'Osun',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            13 => 
            array (
                'id' => 557,
            'ward_name' => 'Egbe-idi (2)',
                'lga' => 'Ilesa West',
                'state' => 'Osun',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            14 => 
            array (
                'id' => 558,
            'ward_name' => 'Ilaje (7)',
                'lga' => 'Ilesa West',
                'state' => 'Osun',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            15 => 
            array (
                'id' => 559,
                'ward_name' => 'Ilase/4',
                'lga' => 'Obokun',
                'state' => 'Osun',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            16 => 
            array (
                'id' => 560,
                'ward_name' => 'Ibala/5',
                'lga' => 'Obokun',
                'state' => 'Osun',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            17 => 
            array (
                'id' => 561,
                'ward_name' => 'Aro/Ojoo',
                'lga' => 'Egbedore',
                'state' => 'Osun',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            18 => 
            array (
                'id' => 562,
                'ward_name' => 'Iragberi 1',
                'lga' => 'Egbedore',
                'state' => 'Osun',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            19 => 
            array (
                'id' => 563,
                'ward_name' => 'Ijimoba',
                'lga' => 'Ejigbo',
                'state' => 'Osun',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            20 => 
            array (
                'id' => 564,
                'ward_name' => 'Isale Osolo',
                'lga' => 'Ejigbo',
                'state' => 'Osun',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            21 => 
            array (
                'id' => 565,
                'ward_name' => 'Oke-Oba 2',
                'lga' => 'Iwo',
                'state' => 'Osun',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            22 => 
            array (
                'id' => 566,
                'ward_name' => 'Oke-Adan 3',
                'lga' => 'Iwo',
                'state' => 'Osun',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            23 => 
            array (
                'id' => 567,
                'ward_name' => 'Oke-Aro/Ibaragun',
                'lga' => 'Ifo',
                'state' => 'Ogun',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            24 => 
            array (
                'id' => 568,
                'ward_name' => 'Coker/Ilepa',
                'lga' => 'Ifo',
                'state' => 'Ogun',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            25 => 
            array (
                'id' => 569,
                'ward_name' => 'Ofada',
                'lga' => 'Obafemi / Owode',
                'state' => 'Ogun',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            26 => 
            array (
                'id' => 570,
                'ward_name' => 'Owode',
                'lga' => 'Obafemi / Owode',
                'state' => 'Ogun',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            27 => 
            array (
                'id' => 571,
                'ward_name' => 'Iberekodo Ward 5',
                'lga' => 'Abeokuta North',
                'state' => 'Ogun',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            28 => 
            array (
                'id' => 572,
                'ward_name' => 'Totoro I',
                'lga' => 'Abeokuta North',
                'state' => 'Ogun',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            29 => 
            array (
                'id' => 573,
                'ward_name' => 'Totoro II',
                'lga' => 'Abeokuta North',
                'state' => 'Ogun',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            30 => 
            array (
                'id' => 574,
                'ward_name' => 'Ogijo',
                'lga' => 'Sagamu',
                'state' => 'Ogun',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            31 => 
            array (
                'id' => 575,
                'ward_name' => 'Ajaka',
                'lga' => 'Sagamu',
                'state' => 'Ogun',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            32 => 
            array (
                'id' => 576,
                'ward_name' => 'Ilisan',
                'lga' => 'Ikenne',
                'state' => 'Ogun',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            33 => 
            array (
                'id' => 577,
                'ward_name' => 'Iperu',
                'lga' => 'Ikenne',
                'state' => 'Ogun',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            34 => 
            array (
                'id' => 578,
                'ward_name' => 'Odogbolu 2',
                'lga' => 'Odogbolu',
                'state' => 'Ogun',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            35 => 
            array (
                'id' => 579,
                'ward_name' => 'Imosan',
                'lga' => 'Odogbolu',
                'state' => 'Ogun',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            36 => 
            array (
                'id' => 580,
                'ward_name' => 'Sango',
                'lga' => 'Ado - Odo / Ota',
                'state' => 'Ogun',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            37 => 
            array (
                'id' => 581,
                'ward_name' => 'Ilogbo',
                'lga' => 'Ado - Odo / Ota',
                'state' => 'Ogun',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            38 => 
            array (
                'id' => 582,
                'ward_name' => 'Ebute',
                'lga' => 'Yewa North',
                'state' => 'Ogun',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            39 => 
            array (
                'id' => 583,
                'ward_name' => 'Ayetoro',
                'lga' => 'Yewa North',
                'state' => 'Ogun',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            40 => 
            array (
                'id' => 584,
                'ward_name' => 'Song Waje',
                'lga' => 'Song',
                'state' => 'Adamawa',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            41 => 
            array (
                'id' => 585,
                'ward_name' => 'Dumne',
                'lga' => 'Song',
                'state' => 'Adamawa',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            42 => 
            array (
                'id' => 586,
                'ward_name' => 'Gwadabawa',
                'lga' => 'Yola North',
                'state' => 'Adamawa',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            43 => 
            array (
                'id' => 587,
                'ward_name' => 'Nassarawo',
                'lga' => 'Yola North',
                'state' => 'Adamawa',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            44 => 
            array (
                'id' => 588,
                'ward_name' => 'Nassarawo',
                'lga' => 'Gerfi',
                'state' => 'Adamawa',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            45 => 
            array (
                'id' => 589,
                'ward_name' => 'Jera Bonyo',
                'lga' => 'Gerfi',
                'state' => 'Adamawa',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            46 => 
            array (
                'id' => 590,
                'ward_name' => 'Gamu',
                'lga' => 'Ganye',
                'state' => 'Adamawa',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            47 => 
            array (
                'id' => 591,
                'ward_name' => 'Bakari Goso',
                'lga' => 'Ganye',
                'state' => 'Adamawa',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            48 => 
            array (
                'id' => 592,
                'ward_name' => 'Jereng',
                'lga' => 'Mayo-Belwa',
                'state' => 'Adamawa',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            49 => 
            array (
                'id' => 593,
                'ward_name' => 'Ganfada',
                'lga' => 'Mayo-Belwa',
                'state' => 'Adamawa',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            50 => 
            array (
                'id' => 594,
                'ward_name' => 'Sabon Pegi ',
                'lga' => 'Numan',
                'state' => 'Adamawa',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            51 => 
            array (
                'id' => 595,
                'ward_name' => 'Numan',
                'lga' => 'Numan',
                'state' => 'Adamawa',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            52 => 
            array (
                'id' => 596,
                'ward_name' => 'Konkol',
                'lga' => 'Maiha',
                'state' => 'Adamawa',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            53 => 
            array (
                'id' => 597,
                'ward_name' => 'Maiha Gari',
                'lga' => 'Maiha',
                'state' => 'Adamawa',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            54 => 
            array (
                'id' => 598,
                'ward_name' => 'Dirbishi',
                'lga' => 'Mubi South',
                'state' => 'Adamawa',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            55 => 
            array (
                'id' => 599,
                'ward_name' => 'Nduku ',
                'lga' => 'Mubi South',
                'state' => 'Adamawa',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            56 => 
            array (
                'id' => 600,
                'ward_name' => 'Gang Mata',
                'lga' => 'Bali',
                'state' => 'Taraba',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            57 => 
            array (
                'id' => 601,
                'ward_name' => 'Maihula',
                'lga' => 'Bali',
                'state' => 'Taraba',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            58 => 
            array (
                'id' => 602,
                'ward_name' => 'Sabon-Gida',
                'lga' => 'Gassol',
                'state' => 'Taraba',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            59 => 
            array (
                'id' => 603,
                'ward_name' => 'Wuro-Jam',
                'lga' => 'Gassol',
                'state' => 'Taraba',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            60 => 
            array (
                'id' => 604,
                'ward_name' => 'Baissa',
                'lga' => 'Kurmi',
                'state' => 'Taraba',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            61 => 
            array (
                'id' => 605,
                'ward_name' => 'Ndaforo',
                'lga' => 'Kurmi',
                'state' => 'Taraba',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            62 => 
            array (
                'id' => 606,
                'ward_name' => 'Kumbo',
                'lga' => 'Donga',
                'state' => 'Taraba',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            63 => 
            array (
                'id' => 607,
                'ward_name' => 'Mararaba',
                'lga' => 'Donga',
                'state' => 'Taraba',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            64 => 
            array (
                'id' => 608,
                'ward_name' => 'Sarkin Kudu 1',
                'lga' => 'Ibi',
                'state' => 'Taraba',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            65 => 
            array (
                'id' => 609,
                'ward_name' => 'Nwonyo 2',
                'lga' => 'Ibi',
                'state' => 'Taraba',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            66 => 
            array (
                'id' => 610,
                'ward_name' => 'Rogo',
                'lga' => 'Takum',
                'state' => 'Taraba',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            67 => 
            array (
                'id' => 611,
                'ward_name' => 'Duste',
                'lga' => 'Takum',
                'state' => 'Taraba',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            68 => 
            array (
                'id' => 612,
                'ward_name' => 'Kassa',
                'lga' => 'Yorro',
                'state' => 'Taraba',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            69 => 
            array (
                'id' => 613,
                'ward_name' => 'Nyaja',
                'lga' => 'Yorro',
                'state' => 'Taraba',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            70 => 
            array (
                'id' => 614,
                'ward_name' => 'Mayo-Lope',
                'lga' => 'Lau',
                'state' => 'Taraba',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            71 => 
            array (
                'id' => 615,
                'ward_name' => 'Jimlari',
                'lga' => 'Lau',
                'state' => 'Taraba',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            72 => 
            array (
                'id' => 616,
                'ward_name' => 'Tamburawa',
                'lga' => 'Dawaki Kudu',
                'state' => 'Kano',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            73 => 
            array (
                'id' => 617,
                'ward_name' => 'Dosan',
                'lga' => 'Dawaki Kudu',
                'state' => 'Kano',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            74 => 
            array (
                'id' => 618,
                'ward_name' => 'Ungogo',
                'lga' => 'Ungogo',
                'state' => 'Kano',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            75 => 
            array (
                'id' => 619,
                'ward_name' => 'Kadawa Ungogo',
                'lga' => 'Ungogo',
                'state' => 'Kano',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            76 => 
            array (
                'id' => 620,
                'ward_name' => 'Sanda',
                'lga' => 'Bunkure',
                'state' => 'Kano',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            77 => 
            array (
                'id' => 621,
                'ward_name' => 'Chirin',
                'lga' => 'Bunkure',
                'state' => 'Kano',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            78 => 
            array (
                'id' => 622,
                'ward_name' => 'Gaya North',
                'lga' => 'Gaya',
                'state' => 'Kano',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            79 => 
            array (
                'id' => 623,
                'ward_name' => 'Balan',
                'lga' => 'Gaya',
                'state' => 'Kano',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            80 => 
            array (
                'id' => 624,
                'ward_name' => 'Rurum Sabon Gari',
                'lga' => 'Rano',
                'state' => 'Kano',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            81 => 
            array (
                'id' => 625,
                'ward_name' => 'Zurgu',
                'lga' => 'Rano',
                'state' => 'Kano',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            82 => 
            array (
                'id' => 626,
                'ward_name' => 'Kore',
                'lga' => 'Danbata',
                'state' => 'Kano',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            83 => 
            array (
                'id' => 627,
                'ward_name' => 'Ajumawa',
                'lga' => 'Danbata',
                'state' => 'Kano',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            84 => 
            array (
                'id' => 628,
                'ward_name' => 'Joda',
                'lga' => 'Gabasawa',
                'state' => 'Kano',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            85 => 
            array (
                'id' => 629,
                'ward_name' => 'Mekiya',
                'lga' => 'Gabasawa',
                'state' => 'Kano',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            86 => 
            array (
                'id' => 630,
                'ward_name' => 'Tofa',
                'lga' => 'Tofa',
                'state' => 'Kano',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            87 => 
            array (
                'id' => 631,
                'ward_name' => 'Wangara Tofa',
                'lga' => 'Tofa',
                'state' => 'Kano',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            88 => 
            array (
                'id' => 632,
                'ward_name' => 'Lambu',
                'lga' => 'Tofa',
                'state' => 'Kano',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            89 => 
            array (
                'id' => 633,
                'ward_name' => 'Buni Yadi',
                'lga' => 'Gujba',
                'state' => 'Yobe',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            90 => 
            array (
                'id' => 634,
                'ward_name' => 'Gujba',
                'lga' => 'Gujba',
                'state' => 'Yobe',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            91 => 
            array (
                'id' => 635,
                'ward_name' => 'Dagona',
                'lga' => 'Bade',
                'state' => 'Yobe',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            92 => 
            array (
                'id' => 636,
                'ward_name' => 'Dawayo',
                'lga' => 'Bade',
                'state' => 'Yobe',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            93 => 
            array (
                'id' => 637,
                'ward_name' => 'Bilal Jawa',
                'lga' => 'Karasuwa',
                'state' => 'Yobe',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            94 => 
            array (
                'id' => 638,
                'ward_name' => 'Karasuwa Garin Guna',
                'lga' => 'Karasuwa',
                'state' => 'Yobe',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            95 => 
            array (
                'id' => 639,
                'ward_name' => 'Afunori',
                'lga' => 'Nguru',
                'state' => 'Yobe',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            96 => 
            array (
                'id' => 640,
                'ward_name' => 'Bulanguwa',
                'lga' => 'Nguru',
                'state' => 'Yobe',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            97 => 
            array (
                'id' => 641,
                'ward_name' => 'Dawasa',
                'lga' => 'Nangere',
                'state' => 'Yobe',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            98 => 
            array (
                'id' => 642,
                'ward_name' => 'Nangere',
                'lga' => 'Nangere',
                'state' => 'Yobe',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            99 => 
            array (
                'id' => 643,
                'ward_name' => 'Mubi Fusami',
                'lga' => 'Fika',
                'state' => 'Yobe',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            100 => 
            array (
                'id' => 644,
                'ward_name' => 'Fika/Anze',
                'lga' => 'Fika',
                'state' => 'Yobe',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            101 => 
            array (
                'id' => 645,
                'ward_name' => 'Mamudo',
                'lga' => 'Potiskum',
                'state' => 'Yobe',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            102 => 
            array (
                'id' => 646,
                'ward_name' => 'Bolewa B',
                'lga' => 'Potiskum',
                'state' => 'Yobe',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            103 => 
            array (
                'id' => 647,
            'ward_name' => 'Jajere - B (Borno Kiji)',
                'lga' => 'Fune',
                'state' => 'Yobe',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            104 => 
            array (
                'id' => 648,
                'ward_name' => 'Kollere Kafaje',
                'lga' => 'Fune',
                'state' => 'Yobe',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
        ));
    }
}
