<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class WardsTableSeeder_1 extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('wards')->insert(array (
            0 => 
            array (
                'id' => 434,
                'ward_name' => 'Tumu',
                'lga' => 'Akko',
                'state' => 'Gombe',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            1 => 
            array (
                'id' => 435,
                'ward_name' => 'Garko',
                'lga' => 'Akko',
                'state' => 'Gombe',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            2 => 
            array (
                'id' => 436,
                'ward_name' => 'Deba',
                'lga' => 'Yamaltu-Deba',
                'state' => 'Gombe',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            3 => 
            array (
                'id' => 437,
                'ward_name' => 'Jagali',
                'lga' => 'Yamaltu-Deba',
                'state' => 'Gombe',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            4 => 
            array (
                'id' => 438,
                'ward_name' => 'Kunde',
                'lga' => 'Dukku',
                'state' => 'Gombe',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            5 => 
            array (
                'id' => 439,
                'ward_name' => 'Zange',
                'lga' => 'Dukku',
                'state' => 'Gombe',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            6 => 
            array (
                'id' => 440,
                'ward_name' => 'Dukkul',
                'lga' => 'Kwami',
                'state' => 'Gombe',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            7 => 
            array (
                'id' => 441,
                'ward_name' => 'Bojude',
                'lga' => 'Kwami',
                'state' => 'Gombe',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            8 => 
            array (
                'id' => 442,
                'ward_name' => 'Ashaka/Magaba',
                'lga' => 'Funakaye',
                'state' => 'Gombe',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            9 => 
            array (
                'id' => 443,
                'ward_name' => 'Bage',
                'lga' => 'Funakaye',
                'state' => 'Gombe',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            10 => 
            array (
                'id' => 444,
                'ward_name' => 'Talasse',
                'lga' => 'Balanga',
                'state' => 'Gombe',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            11 => 
            array (
                'id' => 445,
                'ward_name' => 'Degri',
                'lga' => 'Balanga',
                'state' => 'Gombe',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            12 => 
            array (
                'id' => 446,
                'ward_name' => 'Ture',
                'lga' => 'Kaltungo',
                'state' => 'Gombe',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            13 => 
            array (
                'id' => 447,
                'ward_name' => 'Bule-Kaltin',
                'lga' => 'Kaltungo',
                'state' => 'Gombe',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            14 => 
            array (
                'id' => 448,
                'ward_name' => 'Banganje North',
                'lga' => 'Billiri',
                'state' => 'Gombe',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            15 => 
            array (
                'id' => 449,
                'ward_name' => 'Billiri South',
                'lga' => 'Billiri',
                'state' => 'Gombe',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            16 => 
            array (
                'id' => 450,
                'ward_name' => 'Giwa',
                'lga' => 'Giwa',
                'state' => 'Kaduna',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            17 => 
            array (
                'id' => 451,
                'ward_name' => 'Kakangi',
                'lga' => 'Giwa',
                'state' => 'Kaduna',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            18 => 
            array (
                'id' => 452,
                'ward_name' => 'Tudun Wada Sout',
                'lga' => 'Kaduna South',
                'state' => 'Kaduna',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            19 => 
            array (
                'id' => 453,
                'ward_name' => 'Badiko',
                'lga' => 'Kaduna South',
                'state' => 'Kaduna',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            20 => 
            array (
                'id' => 454,
                'ward_name' => 'Sabon Gari South',
                'lga' => 'Kaduna South',
                'state' => 'Kaduna',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            21 => 
            array (
                'id' => 455,
                'ward_name' => 'Kuya',
                'lga' => 'Ikara',
                'state' => 'Kaduna',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            22 => 
            array (
                'id' => 456,
                'ward_name' => 'Ikara',
                'lga' => 'Ikara',
                'state' => 'Kaduna',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            23 => 
            array (
                'id' => 457,
                'ward_name' => 'Bomo',
                'lga' => 'Sabon Gari',
                'state' => 'Kaduna',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            24 => 
            array (
                'id' => 458,
                'ward_name' => 'Zabi',
                'lga' => 'Sabon Gari',
                'state' => 'Kaduna',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            25 => 
            array (
                'id' => 459,
                'ward_name' => 'Taba',
                'lga' => 'Kudan',
                'state' => 'Kaduna',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            26 => 
            array (
                'id' => 460,
                'ward_name' => 'Kudan',
                'lga' => 'Kudan',
                'state' => 'Kaduna',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            27 => 
            array (
                'id' => 461,
                'ward_name' => 'Chori',
                'lga' => 'Jaba',
                'state' => 'Kaduna',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            28 => 
            array (
                'id' => 462,
                'ward_name' => 'Nduya',
                'lga' => 'Jaba',
                'state' => 'Kaduna',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            29 => 
            array (
                'id' => 463,
                'ward_name' => 'Maigizo',
                'lga' => 'Jema\'a',
                'state' => 'Kaduna',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            30 => 
            array (
                'id' => 464,
                'ward_name' => 'Kagoma',
                'lga' => 'Jema\'a',
                'state' => 'Kaduna',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            31 => 
            array (
                'id' => 465,
                'ward_name' => 'Fada Ward',
                'lga' => 'Kaura',
                'state' => 'Kaduna',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            32 => 
            array (
                'id' => 466,
                'ward_name' => 'Kukum',
                'lga' => 'Kaura',
                'state' => 'Kaduna',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            33 => 
            array (
                'id' => 467,
                'ward_name' => 'Elume',
                'lga' => 'Sapele',
                'state' => 'Delta',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            34 => 
            array (
                'id' => 468,
                'ward_name' => 'Amukpe',
                'lga' => 'Sapele',
                'state' => 'Delta',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            35 => 
            array (
                'id' => 469,
                'ward_name' => 'Okpe',
                'lga' => 'Sapele',
                'state' => 'Delta',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            36 => 
            array (
                'id' => 470,
                'ward_name' => 'Afiesere',
                'lga' => 'Ughelli North',
                'state' => 'Delta',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            37 => 
            array (
                'id' => 471,
                'ward_name' => 'Agbarho 1',
                'lga' => 'Ughelli North',
                'state' => 'Delta',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            38 => 
            array (
                'id' => 472,
                'ward_name' => 'Ekakpamre',
                'lga' => 'Ughelli South',
                'state' => 'Delta',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            39 => 
            array (
                'id' => 473,
                'ward_name' => 'Olumo 1',
                'lga' => 'Ughelli South',
                'state' => 'Delta',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            40 => 
            array (
                'id' => 474,
                'ward_name' => 'Agidiase',
                'lga' => 'Aniocha South',
                'state' => 'Delta',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            41 => 
            array (
                'id' => 475,
                'ward_name' => 'Abbi 1',
                'lga' => 'Ndokwa West',
                'state' => 'Delta',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            42 => 
            array (
                'id' => 476,
                'ward_name' => 'Onicha Okwuani',
                'lga' => 'Ndokwa West',
                'state' => 'Delta',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            43 => 
            array (
                'id' => 477,
                'ward_name' => 'Kwale',
                'lga' => 'Ndokwa West',
                'state' => 'Delta',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            44 => 
            array (
                'id' => 478,
                'ward_name' => 'Okwe',
                'lga' => 'Oshimili South',
                'state' => 'Delta',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            45 => 
            array (
                'id' => 479,
                'ward_name' => 'West End',
                'lga' => 'Oshimili South',
                'state' => 'Delta',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            46 => 
            array (
                'id' => 480,
                'ward_name' => 'Ellu',
                'lga' => 'Isoko North',
                'state' => 'Delta',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            47 => 
            array (
                'id' => 481,
                'ward_name' => 'Ofagbe',
                'lga' => 'Isoko North',
                'state' => 'Delta',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            48 => 
            array (
                'id' => 482,
                'ward_name' => 'Bulu Angiama',
                'lga' => 'Patani',
                'state' => 'Delta',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            49 => 
            array (
                'id' => 483,
                'ward_name' => 'Patani 2',
                'lga' => 'Patani',
                'state' => 'Delta',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            50 => 
            array (
                'id' => 484,
                'ward_name' => 'Laduba Ward',
                'lga' => 'Asa',
                'state' => 'Kwara',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            51 => 
            array (
                'id' => 485,
                'ward_name' => 'Owode/Gbogun',
                'lga' => 'Asa',
                'state' => 'Kwara',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            52 => 
            array (
                'id' => 486,
                'ward_name' => ' Akanbi 4',
                'lga' => 'Ilorin South',
                'state' => 'Kwara',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            53 => 
            array (
                'id' => 487,
                'ward_name' => 'Akanbi 5',
                'lga' => 'Ilorin South',
                'state' => 'Kwara',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            54 => 
            array (
                'id' => 488,
                'ward_name' => 'Magaji Geri',
                'lga' => 'Ilorin West',
                'state' => 'Kwara',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            55 => 
            array (
                'id' => 489,
                'ward_name' => 'Ajikobi',
                'lga' => 'Ilorin West',
                'state' => 'Kwara',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            56 => 
            array (
                'id' => 490,
                'ward_name' => 'Shonga 2',
                'lga' => 'Edu',
                'state' => 'Kwara',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            57 => 
            array (
                'id' => 491,
                'ward_name' => 'Lafiagi 4',
                'lga' => 'Edu',
                'state' => 'Kwara',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            58 => 
            array (
                'id' => 492,
                'ward_name' => 'Eruku',
                'lga' => 'Ekiti',
                'state' => 'Kwara',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            59 => 
            array (
                'id' => 493,
                'ward_name' => 'Oke-Opin/Etan',
                'lga' => 'Ekiti',
                'state' => 'Kwara',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            60 => 
            array (
                'id' => 494,
                'ward_name' => 'Igbo-Idun',
                'lga' => 'Offa',
                'state' => 'Kwara',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            61 => 
            array (
                'id' => 495,
                'ward_name' => 'Ojomu North West',
                'lga' => 'Offa',
                'state' => 'Kwara',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            62 => 
            array (
                'id' => 496,
                'ward_name' => ' Ilale/Erinmope/Imoji',
                'lga' => 'Oke Ero',
                'state' => 'Kwara',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            63 => 
            array (
                'id' => 497,
                'ward_name' => 'Iloffa',
                'lga' => 'Oke Ero',
                'state' => 'Kwara',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            64 => 
            array (
                'id' => 498,
                'ward_name' => 'Erin Ile South',
                'lga' => 'Oyun',
                'state' => 'Kwara',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            65 => 
            array (
                'id' => 499,
                'ward_name' => 'Ijagbo',
                'lga' => 'Oyun',
                'state' => 'Kwara',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            66 => 
            array (
                'id' => 500,
                'ward_name' => 'Bakiyawa',
                'lga' => 'Batagarawa',
                'state' => 'Katsina',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            67 => 
            array (
                'id' => 501,
                'ward_name' => 'Kayauki',
                'lga' => 'Batagarawa',
                'state' => 'Katsina',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            68 => 
            array (
                'id' => 502,
                'ward_name' => 'Ganuwa',
                'lga' => 'Charanchi',
                'state' => 'Katsina',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            69 => 
            array (
                'id' => 503,
                'ward_name' => 'Charanchi',
                'lga' => 'Charanchi',
                'state' => 'Katsina',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            70 => 
            array (
                'id' => 504,
                'ward_name' => 'Dankama',
                'lga' => 'Kaita',
                'state' => 'Katsina',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            71 => 
            array (
                'id' => 505,
                'ward_name' => 'Yanhoho',
                'lga' => 'Kaita',
                'state' => 'Katsina',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            72 => 
            array (
                'id' => 506,
                'ward_name' => 'Kadandani ',
                'lga' => 'Rimi',
                'state' => 'Katsina',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            73 => 
            array (
                'id' => 507,
                'ward_name' => 'Rimi',
                'lga' => 'Rimi',
                'state' => 'Katsina',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            74 => 
            array (
                'id' => 508,
                'ward_name' => 'Bindawa',
                'lga' => 'Bindawa',
                'state' => 'Katsina',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            75 => 
            array (
                'id' => 509,
                'ward_name' => 'Baure ',
                'lga' => 'Bindawa',
                'state' => 'Katsina',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            76 => 
            array (
                'id' => 510,
                'ward_name' => 'Kafin Soli',
                'lga' => 'Kankia',
                'state' => 'Katsina',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            77 => 
            array (
                'id' => 511,
                'ward_name' => 'Tsa Magam ',
                'lga' => 'Kankia',
                'state' => 'Katsina',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            78 => 
            array (
                'id' => 512,
                'ward_name' => 'Jani',
                'lga' => 'Mani',
                'state' => 'Katsina',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            79 => 
            array (
                'id' => 513,
                'ward_name' => 'Mani',
                'lga' => 'Mani',
                'state' => 'Katsina',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            80 => 
            array (
                'id' => 514,
                'ward_name' => 'Goya',
                'lga' => 'Funtua',
                'state' => 'Katsina',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            81 => 
            array (
                'id' => 515,
                'ward_name' => 'Mai Gamji',
                'lga' => 'Funtua',
                'state' => 'Katsina',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            82 => 
            array (
                'id' => 516,
                'ward_name' => 'Minna South',
                'lga' => 'Chanchaga',
                'state' => 'Niger',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            83 => 
            array (
                'id' => 517,
                'ward_name' => 'Nassarawa \'A\'',
                'lga' => 'Chanchaga',
                'state' => 'Niger',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            84 => 
            array (
                'id' => 518,
                'ward_name' => 'Nassarawa \'B\'',
                'lga' => 'Chanchaga',
                'state' => 'Niger',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            85 => 
            array (
                'id' => 519,
                'ward_name' => 'Jere',
                'lga' => 'Paikoro',
                'state' => 'Niger',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            86 => 
            array (
                'id' => 520,
                'ward_name' => 'Gwam',
                'lga' => 'Paikoro',
                'state' => 'Niger',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            87 => 
            array (
                'id' => 521,
                'ward_name' => 'Maje',
                'lga' => 'Suleja',
                'state' => 'Niger',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            88 => 
            array (
                'id' => 522,
                'ward_name' => 'Iku II',
                'lga' => 'Suleja',
                'state' => 'Niger',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            89 => 
            array (
                'id' => 523,
                'ward_name' => 'Kpaki/Takuma',
                'lga' => 'Mokwa',
                'state' => 'Niger',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            90 => 
            array (
                'id' => 524,
                'ward_name' => 'Bokani',
                'lga' => 'Mokwa',
                'state' => 'Niger',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            91 => 
            array (
                'id' => 525,
                'ward_name' => 'Usalle',
                'lga' => 'Kontagora',
                'state' => 'Niger',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            92 => 
            array (
                'id' => 526,
                'ward_name' => 'Magajiya',
                'lga' => 'Kontagora',
                'state' => 'Niger',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            93 => 
            array (
                'id' => 527,
                'ward_name' => 'Wadata',
                'lga' => 'Bida',
                'state' => 'Niger',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            94 => 
            array (
                'id' => 528,
                'ward_name' => 'Mayaki Nadjiya',
                'lga' => 'Bida',
                'state' => 'Niger',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            95 => 
            array (
                'id' => 529,
                'ward_name' => 'Batagi',
                'lga' => 'Gbako',
                'state' => 'Niger',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            96 => 
            array (
                'id' => 530,
                'ward_name' => 'Edozhigi',
                'lga' => 'Gbako',
                'state' => 'Niger',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            97 => 
            array (
                'id' => 531,
                'ward_name' => 'Gaba',
                'lga' => 'Lavun',
                'state' => 'Niger',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            98 => 
            array (
                'id' => 532,
                'ward_name' => 'Egbako',
                'lga' => 'Lavun',
                'state' => 'Niger',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            99 => 
            array (
                'id' => 533,
                'ward_name' => 'Batu',
                'lga' => 'Biriniwa',
                'state' => 'Jigawa',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            100 => 
            array (
                'id' => 534,
                'ward_name' => 'Birniwa',
                'lga' => 'Biriniwa',
                'state' => 'Jigawa',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            101 => 
            array (
                'id' => 535,
                'ward_name' => 'Sarawa',
                'lga' => 'Kafin Hausa',
                'state' => 'Jigawa',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            102 => 
            array (
                'id' => 536,
                'ward_name' => 'Bulangu',
                'lga' => 'Kafin Hausa',
                'state' => 'Jigawa',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            103 => 
            array (
                'id' => 537,
                'ward_name' => 'Fateka',
                'lga' => 'Malam Madori',
                'state' => 'Jigawa',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            104 => 
            array (
                'id' => 538,
                'ward_name' => 'Tashena',
                'lga' => 'Malam Madori',
                'state' => 'Jigawa',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            105 => 
            array (
                'id' => 539,
                'ward_name' => 'Dabaza',
                'lga' => 'Kazaure',
                'state' => 'Jigawa',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            106 => 
            array (
                'id' => 540,
                'ward_name' => 'Kanti',
                'lga' => 'Kazaure',
                'state' => 'Jigawa',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            107 => 
            array (
                'id' => 541,
                'ward_name' => 'Maigatari South',
                'lga' => 'Maigatari',
                'state' => 'Jigawa',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            108 => 
            array (
                'id' => 542,
                'ward_name' => 'Kukayasku',
                'lga' => 'Maigatari',
                'state' => 'Jigawa',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
            109 => 
            array (
                'id' => 543,
                'ward_name' => 'Chaichai',
                'lga' => 'Ringim',
                'state' => 'Jigawa',
                'state_id' => NULL,
                'lga_id' => NULL,
                'status' => 'active',
                'created_at' => '2021-04-18 00:01:01',
                'updated_at' => '2021-04-18 00:01:01',
            ),
        ));
    }
}
