<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class DataEntry extends Model
{
    use HasFactory;

    protected $fillable = [
        '_id',
        'start',
        'end',
        'today',
        'consent',
        'service_cat',
        'serv_received',
        'other_received',
        'freq_visit',
        'year',
        'qtr',
        'month',
        'state',
        'lga',
        'cbo',
        'cboemail',
        'ward',
        'hf',
        'resp_name',
        'child_name',
        'resp_cat',
        'address',
        'phone',
        'resp_edu',
        'mal_info',
        'info_source',
        'prev_how',
        'given_med',
        'side_effect',
        'access_hf',
        'attended_by_hf',
        'offer_anc',
        'receive_ipt',
        'free_mal_aware',
        'denied_access',
        'payto_receive',
        'tested',
        'result_tested',
        'given_meds',
        'duration',
        'attitude',
        'gender_hw',
        'comf',
        'descrimination',
        'assess_quality',
        'hw_qty',
        'hiv_info',
        'infohiv_source',
        'hiv_prev',
        'hivmed_given',
        'hivdrug_side',
        'easilyto_hf',
        'attendedby_hf',
        'ancservice',
        'hivaids_aware',
        'deniedhiv_serv',
        'kindofserv',
        'hivduration',
        'hivattitude',
        'hivgender_hw',
        'hivcomf',
        'hivdescrimination',
        'hivassess_quality',
        'hivhw_qty',
        'tb_info',
        'tb_source',
        'prev_tb',
        'tbdrug_given',
        'drug_sideeffect',
        'tbsideeffect_exp',
        'tbaccess_hf',
        'tbhw',
        'tbanc',
        'freetbaware',
        'tbservdeny',
        'kindtbserv',
        'paytbserv',
        'tbduration',
        'tbattitude',
        'tbgender_hw',
        'tbcomf',
        'tbdescrimination',
        'tbassess_quality',
        'tbhw_qty',
        'store_gps',
        '_submission_time',
    ];
}
